---
controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController

/**:
  joint_state_broadcaster:
    ros__parameters:
      type: joint_state_broadcaster/JointStateBroadcaster

  ackermann_steering_controller:
    ros__parameters:
      type: ackermann_steering_controller/AckermannSteeringController
      traction_joints_names:
      - sauber_right_rear_wheel_joint
      - sauber_left_rear_wheel_joint

      steering_joints_names:
      - sauber_right_steering_hinge_joint
      - sauber_left_steering_hinge_joint

      wheelbase: 0.325
      traction_track_width: 0.2
      steering_track_width: 0.2
      traction_wheels_radius: 0.05

      reference_timeout: 1.0
      use_stamped_vel: true
      enable_odom_tf: true
      odom_frame_id: odom
      base_frame_id: sauber_base_link
