controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController

ackermann_steering_controller:
  ros__parameters:
    traction_joints_names:
    - sauber_left_rear_wheel_joint
    - sauber_right_rear_wheel_joint
    steering_joints_names:
    - sauber_left_steering_hinge_joint
    - sauber_right_steering_hinge_joint

    wheelbase: 0.325
    traction_track_width: 0.2
    steering_track_width: 0.2
    traction_wheels_radius: 0.05

    reference_timeout: 1.0
    use_stamped_vel: true
    enable_odom_tf: true
